import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Check, Copy, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { useCreateInvitation } from '@/features/workspaces/hooks'
import { inviteFormSchema, type InviteFormValues } from '@/schemas'
import { formatDate } from '@/lib/format'
import type { Invitation } from '@/types'

interface InviteDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

/**
 * Create an invite code.
 *
 * Codes are generated by the database, not the browser - the client never
 * chooses its own code, and the RPC re-checks that the caller may invite at all.
 */
export function InviteDialog({ open, onOpenChange }: InviteDialogProps) {
  const [created, setCreated] = useState<Invitation | null>(null)
  const [copied, setCopied] = useState(false)
  const createInvitation = useCreateInvitation()

  const form = useForm<InviteFormValues>({
    resolver: zodResolver(inviteFormSchema),
    defaultValues: { role: 'member', expiresInDays: 7, maxUses: 1, email: '' },
  })

  const handleClose = (next: boolean) => {
    onOpenChange(next)
    if (!next) {
      // Reset only after the dialog is closed, so the code does not vanish
      // mid-animation while the user is still reading it.
      setTimeout(() => {
        setCreated(null)
        setCopied(false)
        form.reset()
      }, 200)
    }
  }

  const onSubmit = async (values: InviteFormValues) => {
    const invitation = await createInvitation.mutateAsync({
      role: values.role,
      expiresInDays: values.expiresInDays,
      maxUses: values.maxUses,
      email: values.email?.trim() ? values.email.trim() : null,
    })
    setCreated(invitation)
  }

  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      toast.error('Could not copy automatically', { description: 'Select the code and copy it.' })
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        {created ? (
          <>
            <DialogHeader>
              <DialogTitle>Invite created</DialogTitle>
              <DialogDescription>
                Share this code with the person you want to invite. It expires on{' '}
                {formatDate(created.expiresAt)}.
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-3 py-2">
              <div className="bg-muted flex items-center justify-between gap-3 rounded-lg border px-4 py-3">
                <code className="font-mono text-lg font-semibold tracking-wider">
                  {created.inviteCode}
                </code>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => void copy(created.inviteCode)}
                  aria-label="Copy invite code"
                >
                  {copied ? (
                    <Check className="size-4 text-emerald-500" aria-hidden="true" />
                  ) : (
                    <Copy className="size-4" aria-hidden="true" />
                  )}
                </Button>
              </div>

              <dl className="text-muted-foreground grid grid-cols-2 gap-2 text-sm">
                <div>
                  <dt className="inline">Role: </dt>
                  <dd className="text-foreground inline capitalize">{created.role}</dd>
                </div>
                <div>
                  <dt className="inline">Uses: </dt>
                  <dd className="text-foreground inline">{created.maxUses}</dd>
                </div>
              </dl>

              {created.inviteUrl && (
                <div className="space-y-1.5">
                  <p className="text-muted-foreground text-xs">Or share this link:</p>
                  <div className="flex gap-2">
                    <Input readOnly value={created.inviteUrl} className="text-xs" />
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => void copy(created.inviteUrl!)}
                      aria-label="Copy invite link"
                    >
                      <Copy className="size-4" aria-hidden="true" />
                    </Button>
                  </div>
                </div>
              )}
            </div>

            <DialogFooter className="gap-2">
              <Button variant="outline" onClick={() => setCreated(null)}>
                Create another
              </Button>
              <Button onClick={() => handleClose(false)}>Done</Button>
            </DialogFooter>
          </>
        ) : (
          <>
            <DialogHeader>
              <DialogTitle>Invite a member</DialogTitle>
              <DialogDescription>
                Generate a code that lets someone join this workspace.
              </DialogDescription>
            </DialogHeader>

            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                <FormField
                  control={form.control}
                  name="role"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Role</FormLabel>
                      <Select value={field.value} onValueChange={field.onChange}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="member">Member - can record transactions</SelectItem>
                          <SelectItem value="admin">Admin - can also manage people</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormDescription>
                        Ownership cannot be granted by invite; promote someone after they join.
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="expiresInDays"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Expires in (days)</FormLabel>
                        <FormControl>
                          <Input {...field} type="number" min={1} max={90} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="maxUses"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Max uses</FormLabel>
                        <FormControl>
                          <Input {...field} type="number" min={1} max={100} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <FormField
                  control={form.control}
                  name="email"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>
                        Email <span className="text-muted-foreground font-normal">(optional)</span>
                      </FormLabel>
                      <FormControl>
                        <Input {...field} type="email" placeholder="teammate@example.com" />
                      </FormControl>
                      <FormDescription>Recorded as a note of who this code was meant for.</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <DialogFooter className="gap-2">
                  <Button type="button" variant="outline" onClick={() => handleClose(false)}>
                    Cancel
                  </Button>
                  <Button type="submit" disabled={createInvitation.isPending}>
                    {createInvitation.isPending && (
                      <Loader2 className="size-4 animate-spin" aria-hidden="true" />
                    )}
                    Create invite
                  </Button>
                </DialogFooter>
              </form>
            </Form>
          </>
        )}
      </DialogContent>
    </Dialog>
  )
}
